export default {
  LOGIN_CUSTOMER: "LOGIN_CUSTOMER",
  LOGIN_EXPERT: "LOGIN_EXPERT",
  LOGIN_CUSTOMER_SUCCESS: "LOGIN_CUSTOMER_SUCCESS",
  LOGIN_EXPERT_SUCCESS: "LOGIN_EXPERT_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
};
